require("darvesh.plugins-setup")
require("darvesh.core.options")
require("darvesh.core.keymaps")
require("darvesh.core.colorscheme")
require("darvesh.plugins.comment")
require("darvesh.plugins.nvim-tree")
require("darvesh.plugins.gitsigns")
require("darvesh.plugins.lualine")
require("darvesh.plugins.telescope")
require("darvesh.plugins.nvim-cmp")
require("darvesh.plugins.lsp.lspsaga")
require("darvesh.plugins.lsp.mason")
require("darvesh.plugins.lsp.lspconfig")
require("darvesh.plugins.lsp.null-ls")
require("darvesh.plugins.autopairs")
require("darvesh.plugins.treesitter")
require("darvesh.plugins.toggleterm")
require("darvesh.plugins.copilot")
require("darvesh.plugins.nvim-web-devicons")

-- This isn't working as I would expect :/
vim.cmd([[set guifont=/Users/darveshgorhe/Library/Fonts/MesloLGLNerdFontMono-Regular:h12]])
